#EdgeCore = Built by: PickleZ

messages: #{player} represents player (individual)
  - "&7Join our forums, and get that sick =(e)= tag! www.edge-gamers.com!"
  - "&7Use /clan to view what clan you are in, and the perks you recieve!"
  - "&7Make sure to claim your daily, weekly, and monthly packages at spawn!"
  - "&7Please report all bugs on the forums under the Kingdoms Bug report thread!"
  - "&7Make sure to utilize your 48h kits!"
  - "&7Use /mineworld to purchase a mineworld ticket!"